### ISSUE TITLE
Error loading mods

### ISSUE THREAD

**Issue by Catomax262** [PianoManu/BlockCarpentry#69] opened 2023-01-09 21:46 UTC
log: https://crashy.net/I609pO4GWCcrL8L1ziqL

**Comment by PianoManu** [comment] 2023-10-10 18:59
This is probably caused by another mod altering the waterlogging mechanism. However, the issue should be fixed in Version 0.4.0 because of major rewrites

**Closed as completed by PianoManu** 2023-10-10 18:59 UTC
Labels: bug, fixed/implemented
