### ISSUE TITLE
1.16.3

### ISSUE THREAD

**Issue by Lerizo** [PianoManu/BlockCarpentry#8] opened 2020-10-01 18:45 UTC
I dont know if this is the right place to do it but i have a question
Will 1.16.3 comatibility come soon?
and if so can you give an estimate time?

**Comment by PianoManu** [comment] 2020-10-02 09:28
Yup. I'm planning on releasing some sort of 1.16.3-beta soon. AFAIK I don't have to really change anything in code besides the dependencies and the mods.toml, but it might cause some problems. I'll try that out in the future :)

**Comment by Lerizo** [comment] 2020-10-02 13:49
Thanks, im probably making a server for my friend with cool mods and this is definitely one

**Comment by lycanthrope7** [comment] 2020-10-06 11:20
I've just tested version 0.3.1 of this mod in MC 1.16.3 using Forge 34.1.0. It loaded fine, and the frames can be placed, but as soon as you apply a texture, they become invisible. I tried with the slopes at first as they were my favourite part of the original Carpenter's blocks. When that turned invisible I tried the stairs with the same result.

**Comment by PianoManu** [comment] 2020-10-06 13:19
Do you have optifine installed? Because sadly, it does not work together with optifine...

**Comment by Lerizo** [comment] 2020-10-06 13:33
Will it be compatible with Optifine someday or that’s not in your plans?

**Comment by PianoManu** [comment] 2020-10-06 13:44
Well it would be great, if it worked with Optifine, but I'm a pretty new and inexperienced modder, so I don't know if this is something I could do...

**Comment by PianoManu** [comment] 2020-10-06 13:47
AFAIK the problem is, that all blocks are rendered transparent (because you might want transparent blocks e.g. glass, slime, etc.), and I think optifine changes something how this is handled internally. I'll look into this issue, but I don't know whether and when I will get this to work...

**Comment by lycanthrope7** [comment] 2020-10-07 01:24
Ah, ok. Yes I do have optifine. I might have a play with optifine's settings and see if that makes any difference. I'll let you know if I have any luck. Meanwhile, have you tried reaching out to some other mod makers? Someone might have already solved this issue with their mod, and can tell you how they did it. I wsh you all the best. I loved Carpenter's Blocks and I'm thrilled that someone has taken the time to resurrect it.

**Comment by PianoManu** [comment] 2020-10-08 09:13
I have an idea for a work-around: adding a config entry to enable/disable block opacity (because it works, when all frame/illusion blocks are non-transparent). So if you have optifine installed, you enable it (meaning that glass is no longer transparent, and it will look weird), and for default, it is disabled. What do you think of this?

**Comment by PianoManu** [comment] 2020-10-08 09:25
Since the initial issue (porting to 1.16.3) is solved, I'll close this thread

**Closed by PianoManu** 2020-10-08 09:25 UTC
Labels: enhancement, useful to read
