### ISSUE TITLE
game crash when fill a framed door with a block

### ISSUE THREAD

**Issue by WildWolve** [PianoManu/BlockCarpentry#71] opened 2023-02-20 10:03 UTC
hi there.
first of all, i loved the fact that you let the old carpenters blocks mod return to life with your work here. it was one of my most favorites in the MC 1.7.10
and i missed it since then deeply. so .... thank you for making the mod now

now ...
i installed blockcarpentry (singleplayer only, no server, MC1.19.2 / forge) placed a framed door and filled a normal spruce plank in the door
the filled half of the door dissapeared, the game froze and crashed. it also crashed everytime i tryed to reload the savegame.

installed mods are:
Architectury API
Balm
Better FPS
Biomes oplenty
Blockcarpentry (obviously)
Bookshelf
Chalk
Chisels & bits
Cloth Config API
Configured
Corpse
Crafting tweaks
Croptopia
Entity collision FPS fix
FPS reducer
FTB cunks
FTB Libary
FTB Teams
Falling tree
Fastleaf decay
Functional Storage
Inventory sorter
Iron chests
Item collectors
Jade ?
Journeymap
JEI
JER
Light overlay
Mobcatcher
Moonlight LIB
Optifine
Paladins Furniture
Patchouli
Polymorph
Re-Chiseled
Saturn
simply light
Sophisticeted Backpacks
Sophisticated Core
Sophisticated Storage
supermartijn642's confing and core lib
supplementaries
Terrablender
Titanium
Torchmaster
Trashcans
spark

crashreport:
[crash-2023-02-20_10.44.29-client.txt](https://github.com/PianoManu/BlockCarpentry/files/10783181/crash-2023-02-20_10.44.29-client.txt)

**Comment by PianoManu** [comment] 2023-02-20 22:07
Hey, thanks for reporting. I will look into this ASAP. Right now I'm not having much time as I'm currently writing my bachelor's thesis. But when I find some free time and concentration, I will fix it. Thanks again.

Regards, Manu

**Comment by PianoManu** [comment] 2023-11-05 09:20
I don't know whether this problem still exists, I was unable to reproduce this error. I have thoroughly reviewed the code and rewritten, so you could test again in the newest version. Even if the issue with the invisible part still exists, the game should no longer crash, since I now wrapped a major part of the rendering stuff with try-catches. This should eliminate most crashes arising from modded blocks. Therefore, I'm now closing this issue :)
Regards, Manu

**Closed as completed by PianoManu** 2023-11-05 09:20 UTC
Labels: fixed - needs testing
