### ISSUE TITLE
Crash w/ More Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [PianoManu/BlockCarpentry#25] opened 2020-12-19 22:36 UTC
`Minecraft v1.16.4`
`Forge v35.1.13`
`Block Carpentry v0.3.4`
[`More Waterlogging v1.4`](https://www.curseforge.com/minecraft/mc-mods/more-waterlogging)

The game crashes on launch, and from the crash log, it looks like it is caused by an interaction between this mod and More Waterlogging. It seems to happen with at least four of the BlockCarpentry blocks.
[Crash Report](https://gist.github.com/WenXin20/fc94ecd909463f425ee98b898d055993)

**Comment by PianoManu** [comment] 2020-12-22 09:49
Weird.... I'll try to fix this when the slopes are working. That's what I'm currently trying to fix,,,

**Comment by WenXin20** [comment] 2020-12-22 16:23
Thanks. It crashes because More Waterlogging adds waterlogging to blocks that normally doesn't have waterlogging.

**Comment by PianoManu** [comment] 2020-12-23 09:51
Yeah makes sense. Thank you for reporting

**Comment by PianoManu** [comment] 2022-05-31 11:17
Just now, I installed More Waterlogging (v.1.5) and the latest version of my mod, and I did not get any errors and the waterlogging works fine for blocks that otherwise would not have the waterlogged-attribute (like beds or pressure plates). Also I read in the changelog of More Waterlogging that they switched to the [Statement library](https://www.curseforge.com/minecraft/mc-mods/statement) for compatibility reasons, so I guess, the problem actually wasn't caused by my mod but by More Waterlogging

I guess it is no longer important, since 1.16 is outdated, but this problem is solved and I'm closing this issue now :)

Regards, Manu

**Closed by PianoManu** 2022-05-31 11:17 UTC
Labels: bug, fixed/implemented
