### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [PianoManu/BlockCarpentry#1] opened 2020-08-28 19:06 UTC
`Minecraft v1.15.2`
`Forge v31.2.36`
`Block Carpentry v0.6.0`

I had placed the carpentry slab, but when I tried to place a regular slab on top, I accidentally placed it in the carpentry slab, but it was given the missing texture instead. And then when I broke the carpentry slab, the server crashed instead.
[Crash Report](https://gist.github.com/WenXin20/10214a5d01102e059cbb5bb6d508f584)

**Comment by PianoManu** [comment] 2020-08-28 19:25
Yeah I can imagine. This currently only works for vanilla blocks. I'm working on a solution. Thanks for reporting!

**Comment by WenXin20** [comment] 2020-08-28 19:33
There is a mod called [Fake Blocks](https://github.com/henkelmax/fake-blocks) which adds something similar, and it works with any modded full block. Maybe take a look to see how they're doing it?

**Comment by PianoManu** [comment] 2020-08-28 21:18
Thanks for the hint! I'll do that!

**Comment by PianoManu** [comment] 2020-08-28 21:21
Oh well, the problem is, they're using tile entity renderers, while I use baked models extracting the texture (that's how you can get e.g. a block with the crafting-table-top texture). So it works quite different. I hope to get it to work soon...

**Comment by WenXin20** [comment] 2020-08-28 22:08
Ah, I see. Good luck!
Also, I think the server crashes when the carpentry blocks drop the items when broken.

**Comment by Shindur** [comment] 2020-09-06 01:48
I'm getting a similar issue, except I place down the frame, right click in a vanilla block (polished blackstone bricks) and the server crashes, client is fine. When I re-enter my world the frame is there and not rendering the block, but I can break it without crashing me or the server. 

Link to report I filled out on the pack I'm playing w/ the crash log: https://github.com/NillerMedDild/Enigmatica6/issues/257

**Comment by PianoManu** [comment] 2020-09-09 17:03
Should now be fixed. I've tested all three versions (1.15.1/1.15.2 **0.7.0**, 1.16.1 **0.2.0**, 1.16.2 **0.2.1**) together with different mods (mainly with "Biomes'o'Plenty" and "Oh the Biomes You'll Go") and I didn't get any error anymore. I guess it does _really_ work by now. Thanks again for reporting!
Regards, Manu

**Comment by PianoManu** [comment] 2020-09-12 11:11
Alright, I've found another bug causing server crashes (when breaking blocks and when coloring door/trapdoor windows). This will be fixed in version 0.7.1 (1.15.1/1.15.2, already fixed and tested both on singleplayer and server), 0.2.1 (1.16.1) and 0.2.2 (1.16.2). I think I can close this issue now...

**Closed by PianoManu** 2020-09-12 11:11 UTC
Labels: bug, help wanted
