### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by pushrat1698** [PianoManu/BlockCarpentry#37] opened 2021-04-25 19:07 UTC
I have a server that me and my friends play on, but when we added block carpentry it caused our game to crash whenever we placed a block carpentry block with this error:
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry Object not present: blockcarpentry:frameblock
Exit Code: -1

**Comment by PianoManu** [comment] 2021-05-01 09:55
Hey, are you sure, you've installed everything correctly? Are you using the latest version of the mod and which forge version are you using? It would also be helpful, if you could provide the whole crash report (you can find it in your modpack folder in the "crash-reports"-directory.

Basically, I think the problem is related to an incorrect installation, but I can't help much without the full log.
Regards, Manu

**Comment by PianoManu** [comment] 2021-08-19 13:15
No further information regarding this problem... I'll close this issue now. Feel free to reopen this issue, if you provide additional information

**Closed by PianoManu** 2021-08-19 13:15 UTC
Labels: more information needed

**Comment by Thspooks** [comment] 2023-08-13 08:13
Im having same issue. I can provide more information
